### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by paambaati** [HAKASHUN/grunt-remove-usestrict#1]
Can you add a LICENSE file to the project? I'm using this at work and company policy needs me to specify the license for each component I use.

**Comment by HAKASHUN** [comment]
https://github.com/HAKASHUN/grunt-remove-usestrict/commit/58207aff778c382ad6fca4998f96f7c9bd37d765

I added a LICENCE file. 
This project is released under the MIT License.

**Comment by paambaati** [comment]
@HAKASHUN Fantastic, thanks!
